[project]
name = 'Blockchain-Based-Specialized-Medical-Simulation-Training'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.instructor-certification]
path = 'contracts/instructor-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.scenario-management]
path = 'contracts/scenario-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulator-registration]
path = 'contracts/simulator-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
